version: "3.7"

services:
  mongo:
    image: mongo
    hostname: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - ./compose/mongo/:/docker-entrypoint-initdb.d/
    command: "--replSet rs0"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - back
      - front
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf

  back:
    build:
      context: .
      dockerfile: ./compose/back/Dockerfile-dev
    command: sh /start-dev.sh
    environment:
      - NODE_ENV=development
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=admin
      - BROWSER_HOST=http://localhost
    depends_on:
      - mongo
    ports:
      - 1337:1337
    volumes:
      - ./back/:/home/service/back/
      - back_node_modules:/home/service/back/node_modules/

  front:
    build:
      context: .
      dockerfile: ./compose/front/Dockerfile-dev
    command: sh /start-dev.sh
    environment:
      - NODE_ENV=development
      - SOCKET_ADDRESS=http://218.144.17.243:3333
    ports:
      - 3000:3000
    volumes:
      - ./front/:/home/service/front/
      - front_node_modules:/home/service/front/node_modules/

volumes:
  mongodata:
  back_node_modules:
  front_node_modules: